
dataset:
    name: Application_People
    description: Staging table People
    enabled: true
    type: staging
    load_sytle: default
    load_method: default

columns:
  - ordinal: 1            
    name: PersonID            
    data_type: int                                                                        
            
  - ordinal: 2            
    name: FullName            
    data_type: nvarchar            
    length: 50                                                            
            
  - ordinal: 3            
    name: PreferredName            
    data_type: nvarchar            
    length: 50                                                            
            
  - ordinal: 4            
    name: SearchName            
    data_type: nvarchar            
    length: 101                                                            
            
  - ordinal: 5            
    name: IsPermittedToLogon            
    data_type: bit                                                                        
            
  - ordinal: 6            
    name: LogonName            
    data_type: nvarchar            
    length: 50                                    
    is_nullable: true                        
            
  - ordinal: 7            
    name: IsExternalLogonProvider            
    data_type: bit                                                                        
            
  - ordinal: 8            
    name: HashedPassword            
    data_type: varbinary            
    length: -1                                    
    is_nullable: true                        
            
  - ordinal: 9            
    name: IsSystemUser            
    data_type: bit                                                                        
            
  - ordinal: 10            
    name: IsEmployee            
    data_type: bit                                                                        
            
  - ordinal: 11            
    name: IsSalesperson            
    data_type: bit                                                                        
            
  - ordinal: 12            
    name: UserPreferences            
    data_type: nvarchar            
    length: -1                                    
    is_nullable: true                        
            
  - ordinal: 13            
    name: PhoneNumber            
    data_type: nvarchar            
    length: 20                                    
    is_nullable: true                        
            
  - ordinal: 14            
    name: FaxNumber            
    data_type: nvarchar            
    length: 20                                    
    is_nullable: true                        
            
  - ordinal: 15            
    name: EmailAddress            
    data_type: nvarchar            
    length: 256                                    
    is_nullable: true                        
            
  - ordinal: 16            
    name: Photo            
    data_type: varbinary            
    length: -1                                    
    is_nullable: true                        
            
  - ordinal: 17            
    name: CustomFields            
    data_type: nvarchar            
    length: -1                                    
    is_nullable: true                        
            
  - ordinal: 18            
    name: OtherLanguages            
    data_type: nvarchar            
    length: -1                                    
    is_nullable: true                        
            
  - ordinal: 19            
    name: LastEditedBy            
    data_type: int                                                                        
            
  - ordinal: 20            
    name: ValidFrom            
    data_type: datetime2                                                                        
            
  - ordinal: 21            
    name: ValidTo            
    data_type: datetime2                                                                        
            